{% set name = "aiida-orca" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: b17ef20197da61462c04ca74c3f120dd2827ec9d777e003c71ba0452640284f7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - reentry
  run:
    - aiida-core.atomic_tools >=1.0.0,<2
    - cclib
    - python >=3.7

test:
  imports:
    - aiida_orca
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pzarabadip/aiida-orca
  summary: AiiDA plugin for ORCA code
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - chrisjsewell
